# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: "task --list-all"
    cmds:
      - task --list-all

  hadolint:
    desc: "Run hadolint"
    cmds:
      - find . -name 'Dockerfile*' | xargs -r hadolint

  mypy:
    desc: "Run mypy"
    cmds:
      - uv run mypy --no-incremental ./src ./tests

  ty:
    desc: "Run ty"
    cmds:
      - uv run ty check ./src ./tests

  ruff:
    desc: "Run Ruff check and format"
    cmds:
      - uv run ruff check ./src ./tests --fix
      - uv run ruff format ./src ./tests
    ignore_error: true

  check:
    desc: "Run all static analysis tools"
    cmds:
      - task: hadolint
      - task: mypy
      - task: ty
      - task: ruff
    ignore_error: true

  test:
    desc: "Run pytest"
    cmds:
      - uv run pytest
  test-cov:
    desc: "Run pytest with coverage"
    cmds:
      - uv run pytest -v --cov=.
