name: template-python-uv
services:
  workspace:
    image: template-python-uv:dev
    build:
      dockerfile: ../.devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace
    user: "vscode"
    tty: true
