FROM python:3.11-slim-bookworm

SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    openssh-client \
    # gpg gpg-agent pinentry-curses \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=appuser
RUN useradd --create-home $USERNAME --shell /bin/bash
USER $USERNAME

RUN mkdir -p "$HOME/.local/bin" && chmod +x "$HOME/.local/bin"

# https://github.com/hadolint/hadolint
RUN curl -LsSf https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o "$HOME/.local/bin/hadolint" \
    && chmod +x "$HOME/.local/bin/hadolint"

# https://github.com/go-task/task
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "$HOME/.local/bin" v3.42.1

# https://github.com/astral-sh/uv
# hadolint ignore=SC2086
RUN curl -LsSf https://astral.sh/uv/0.6.11/install.sh | bash \
    && echo 'eval "$(uv generate-shell-completion bash)"' >> $HOME/.bashrc \
    && echo 'eval "$(uvx --generate-shell-completion bash)"' >> $HOME/.bashrc

ENV PYTHONUNBUFFERED=true \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=true \
    UV_PYTHON_DOWNLOADS=never

WORKDIR /app
