FROM debian:stable-slim AS base

SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

ENV LANG=C.UTF-8

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    git \
    openssh-client \
    gpg gpg-agent pinentry-curses \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

FROM base AS dev

SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

ARG USERNAME=vscode
RUN useradd --create-home $USERNAME --shell /bin/bash
USER $USERNAME

RUN mkdir -p "$HOME/.local/bin" && chmod 755 "$HOME/.local/bin"


# hadolint
# https://github.com/hadolint/hadolint
RUN curl -LsSf https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-Linux-x86_64 -o "$HOME/.local/bin/hadolint" \
    && chmod +x "$HOME/.local/bin/hadolint"

# Task
# https://github.com/go-task/task
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "$HOME/.local/bin" v3.51.1

# uv
# https://github.com/astral-sh/uv
# hadolint ignore=SC2016
RUN curl -LsSf https://astral.sh/uv/0.11.15/install.sh | bash \
    && echo 'eval "$(uv generate-shell-completion bash)"' >> "$HOME/.bashrc" \
    && echo 'eval "$(uvx --generate-shell-completion bash)"' >> "$HOME/.bashrc"

ENV PYTHONUNBUFFERED=true \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=true
RUN "$HOME/.local/bin/uv" python install 3.14

WORKDIR /workspace
